#!/usr/bin/env bash
npm run build:base
npm run build:dashboard
npm run build:blog
npm run build:book
npm run build:email
npm run build:finance
npm run build:good
npm run build:hr
npm run build:manufacture
npm run build:marketing
npm run build:profile
npm run build:teaching
npm run build:work
npm run build:shift
npm run build:dashboard
npm run build:workShift
npm run build:landingPage
npm run build:order
npm run build:survey
npm run build:business
npm run build:notification
